name: Format code

# GitHub Actions何も分からない :(
# https://zenn.dev/arsaga/articles/bf20daf4b35ccc

# プルリクエスト時に実行する
# https://docs.github.com/ja/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  format:
    name: format
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.10"]
        node-version: ["20"]
    permissions:
      contents: write
    steps:
      - name: Checkout repository # リポジトリのチェックアウト
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python ${{ matrix.python-version }} # Pythonのセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install black and isort # black、pipのインストール
        run: |
          python -m pip install --upgrade pip
          pip install black isort

      - name: Format with black # blackを使ってフォーマット
        run: black .

      - name: Format with isort # isortを使ってインポートを整理
        run: isort .

      - name: Set up Node.js ${{ matrix.node-version }} # Node.jsのセットアップ
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install prettier # prettierのインストール
        run: |
          npm install -g prettier

      - name: Format with prettier # prettierを使ってフォーマット
        run: prettier --write '*.{html,css,js}'

      - name: Auto commit # 自動コミット
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Auto code format
